import type { Metadata } from "next";
import "./globals.css";
import {geistMono, geistSans} from "@/app/ui/fonts";
import {ThemeProvider} from "next-themes";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
          {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
